#!/bin/sh
#configure core php
cat > /usr/local/etc/php-fpm.d/www.conf <<- EOF
[global]
error_log = ${FPM_ERROR_LOG}

[www]
user = www-data
group = www-data
listen = /var/run/php-fpm.sock
ping.path = ${FPM_PING_PATH}
ping.response = ${FPM_PING_RESPONSE}
pm = ${FPM_PM}
pm.status_path = ${FPM_PM_STATUS_PATH}
pm.max_children = "${FPM_PM_MAX_CHILDREN}";
pm.start_servers = "${FPM_PM_START_SERVERS}";
pm.min_spare_servers = "${FPM_PM_MIN_SPARE_SERVERS}";
pm.max_spare_servers = "${FPM_PM_MAX_SPARE_SERVERS}";
pm.process_idle_timeout  = "${FPM_PROCESS_MAX_IDLE_TIMEOUT}";
pm.max_requests = ${FPM_PM_MAX_REQUESTS};
request_slowlog_timeout = "${FPM_REQUEST_SLOWLOG_TIMEOUT}";
slowlog = "${FPM_SLOWLOG}";

php_value[display_errors] = ${PHP_INI_DISPLAY_ERRORS}
php_value[display_startup_errors] = ${PHP_INI_DISPLAY_STARTUP_ERRORS}
php_value[error_reporting] = ${PHP_INI_DISPLAY_STARTUP_ERRORS}
php_value[log_errors] = ${PHP_INI_LOG_ERRORS}
php_value[error_log] = ${PHP_INI_LOG_ERRORS}
php_value[max_input_time] = ${PHP_INI_LOG_ERRORS}
php_value[max_execution_time] = ${PHP_INI_MAX_EXECUTION_TIME}
php_value[memory_limit] = ${PHP_INI_MEMORY_LIMIT}
php_value[post_max_size] = ${PHP_INI_POST_MAX_SIZE}
php_value[upload_max_filesize] = ${PHP_INI_UPLOAD_MAX_FILESIZE}
EOF

## Configure new relic
#if [ "${NEW_RELIC_ENABLED}" = true ]; then
#    echo "Enabling new relic"
#    cp "${PHP_DBG_PATH}/newrelic.so" "${PHP_LIB_PATH}/newrelic.so"
#    cp "${PHP_DBG_PATH}/newrelic.ini" "${PHP_CONF_D}/newrelic.ini"
#
#    sed -ie "s/REPLACE_WITH_REAL_KEY/${NEW_RELIC_KEY}/" ${PHP_CONF_D}/newrelic.ini
#	sed -i -e "s/PHP Application/${NEW_RELIC_APP_NAME}/g" ${PHP_CONF_D}/newrelic.ini
#
#    if [ "${DEBUG_CONFIG_FILES}" = true ]; then
#        cat "${PHP_CONF_D}/newrelic.ini"
#    fi
#else
#    echo "Disabling new relic"
#    rm -f "${PHP_LIB_PATH}/newrelic.so"
#    rm -f "${PHP_CONF_D}/newrelic.ini"
#fi
#
## Configure phpd debugger
#if [ "${PHPED_ENABLED}" = true ]; then
#    echo "Enabling Nusphere PHPed"
#    cp "${PHP_DBG_PATH}/dbg-php-7.2.so" "${PHP_LIB_PATH}/"
#
#    {
#    echo "zend_extension=\"${PHP_LIB_PATH}/dbg-php-7.2.so\""
#    echo "[debugger]"
#    echo "debugger.hosts_allow=\"${PHP_DBG_ALLOWED_HOSTS}\""
#    echo "debugger.hosts_deny=ALL"
#    echo "debugger.ports=7869"
#    }  >> "${PHP_CONF_D}/debugger.ini"
#    if [ "${DEBUG_CONFIG_FILES}" = true ]; then
#        cat "${PHP_CONF_D}/debugger.ini"
#    fi
#
#else
#    echo "Disabling Nusphere PHPed"
#    rm -f "${PHP_LIB_PATH}/dbg-php-7.2.so"
#    rm -f "${PHP_CONF_D}/debugger.ini"
#fi

php-fpm -F